//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CFToolbox.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_CFTOOLBOX_DIALOG            102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDR_MAINFRAME                   128
#define IDR_ICON32                      128
#define IDD_ENTER_PASSWORD              129
#define IDD_TAB_PREFERENCES             130
#define IDD_QUESTION                    131
#define IDD_TAB_ADD                     132
#define IDD_TAB_LOGS                    133
#define IDD_PROGRESS                    135
#define IDD_TAB_FILES                   136
#define IDR_FILES_MENU                  138
#define IDR_ICON16                      139
#define IDR_APPS_MENU                   139
#define IDB_BITMAP1                     141
#define IDD_PROPERTIES                  142
#define IDD_TAB_APPS                    143
#define IDI_EMPTY                       144
#define IDI_ICON1                       145
#define IDD_APP_PROPERTIES              147
#define IDD_CHOOSE_ACCOUNT              149
#define IDD_TAB_BANDWIDTH               150
#define IDD_TAB_HELP                    155
#define IDR_TASKS_MENU                  157
#define IDR_ADDFILES_MENU               158
#define IDR_ADDAPPS_MENU                159
#define IDI_ICON2                       161
#define IDI_ICON3                       162
#define IDI_ICON4                       163
#define IDC_TAB                         1002
#define IDC_LOGS                        1004
#define IDC_ACCOUNT                     1005
#define IDC_PASSWORD                    1006
#define IDC_SAVE_PASSWORD               1007
#define IDC_STEAMGUARD                  1007
#define IDC_EDIT1                       1008
#define IDC_MAX_TASKS                   1008
#define IDC_PATH                        1008
#define IDC_MAX                         1008
#define IDC_STEAMGUARD2                 1008
#define IDC_CURRENT                     1009
#define IDC_EDIT2                       1010
#define IDC_VALUE                       1010
#define IDC_COMMONPATH                  1010
#define IDC_COMMAND                     1010
#define IDC_FILE                        1010
#define IDC_MINIMUM                     1010
#define IDC_TYPE                        1011
#define IDC_FILECOMMAND                 1011
#define IDC_REMAINING                   1011
#define IDC_ACCOUNTS                    1012
#define IDC_ID                          1012
#define IDC_CSIZE                       1013
#define IDC_VERSION                     1014
#define IDC_COMPLETION                  1015
#define IDC_BLOCKS                      1016
#define IDC_REMEMBER                    1017
#define IDC_DESCRIPTION                 1017
#define IDC_FOLDERD                     1018
#define IDC_NORESET                     1018
#define IDC_KEY                         1019
#define IDC_HOST                        1022
#define IDC_PORT                        1023
#define IDC_LOGIN                       1024
#define IDC_TICKET_STATUS               1026
#define IDC_BUTTON6                     1027
#define IDC_DO_LOGIN                    1028
#define IDC_EXPORT                      1029
#define IDC_DO_DISCONNECT               1029
#define IDC_IMPORT                      1030
#define IDC_SET                         1031
#define IDC_Question                    1032
#define IDC_DELETE                      1032
#define IDC_LEVEL                       1033
#define IDC_UPDATECDR                   1034
#define IDC_AUTOMATICUPDATE             1035
#define IDC_PROGRESS                    1036
#define IDC_SET2                        1036
#define IDC_MESSAGE                     1037
#define IDC_SET3                        1037
#define IDC_FILES                       1038
#define IDC_LANGUAGE                    1038
#define IDC_TASKS                       1039
#define IDC_SET4                        1039
#define IDC_GROUP                       1040
#define IDC_SPIN1                       1041
#define IDC_VALIDATE_PATCHS             1042
#define IDC_APPS                        1043
#define IDC_SHARING                     1043
#define IDC_NAME                        1044
#define IDC_SECURED                     1044
#define IDC_DEVELOPPER                  1045
#define IDC_BANDWIDTH                   1045
#define IDC_MANUALS                     1046
#define IDC_MINI                        1046
#define IDC_GCFS                        1047
#define IDC_VALIDATE_DOWNLOADS          1047
#define IDC_PROPERTIES                  1048
#define IDC_SECURED2                    1048
#define IDC_MANUAL                      1049
#define IDC_WAIT_FILE                   1050
#define IDC_COMMON                      1050
#define IDC_WAIT_APP                    1051
#define IDC_ACCOUNT_LIST                1051
#define IDC_BANDWIDTH_GRAPH             1053
#define IDC_COMBO1                      1054
#define IDC_APP_DBLCLICK                1055
#define IDC_EXPLORER2                   1056
#define IDC_EXPLORER1                   1057
#define IDC_FROM                        1059
#define IDC_HIDER                       1060
#define IDC_KILL                        1061
#define IDC_STOP                        1062
#define IDC_HIDEFULL                    1062
#define IDC_DOWNLOAD                    1064
#define IDC_GCF_PATH                    1066
#define IDC_GCF_BROWSE                  1067
#define IDC_PATCH_PATH                  1068
#define IDC_PATCH_BROWSE                1069
#define IDC_GMTFRM                      1070
#define IDC_FILESFRM                    1071
#define IDC_ACCLBL                      1072
#define IDC_FILE_DBLCLICK               1073
#define IDC_NOTFOUND                    1074
#define IDC_BUTTON1                     1075
#define IDC_CHECK1                      1076
#define IDC_CLEAR                       1082
#define ID_ROOT_PAUSE                   32778
#define ID_ROOT_DOWNLOAD                32778
#define ID_ROOT_ACCOUNT                 32779
#define ID_ROOT_DELETE                  32780
#define ID_ROOT_PROPERTIES              32782
#define ID_ROOT_PATCHS_MAKEARCHIVE      32783
#define ID_ROOT_PATCHS_MAKEUPDATE       32784
#define ID_ROOT_PATCHS_APPLYUPDATE      32785
#define ID_ROOT_OPEN                    32787
#define ID_ROOT_VALIDATE                32788
#define ID_ROOT_CORRECT                 32789
#define ID_ROOT_CANCEL                  32790
#define ID_ROOT_COPY                    32791
#define ID_ROOT_RUN                     32792
#define ID_ROOT_PAUSE_                  32793
#define ID_ROOT_MINI                    32794
#define ID_ROOT_SELECT                  32795

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        164
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         1077
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
